// Shared mutable state
export const state = {
    audioContext: null,
    analyserNode: null,
    leftAnalyser: null,
    rightAnalyser: null,
    mediaSource: null,
    splitterNode: null,
    isolationInputGain: null,
    isolationDryGain: null,
    isolationWetGain: null,
    isolationFilters: [],
    isolationMode: 'full',
    isolationMix: 1.0,
    isPlaying: false,
    frequencyData: null,
    timeData: null,
    leftFreqData: null,
    rightFreqData: null,
    animationFrames: {},
    currentAudioFile: null,
    uploadedFileUrl: null,
    currentAudioDataUrl: null,
    currentAudioClipDataUrl: null,
    currentAudioClipGeneratedAtMs: 0,
    aiStreamDestination: null,
    pendingFile: null,
    audioElement: null,
};